---
admin:
  title:
    action_rejected: 未识别指示，请重新输入指令
    apply_cancel: 已取消申请
    apply_invalid_failed: 头衔名称无效，取消申请
    apply_invalid_rejected: 头衔名称无效，请重新输入
    apply_length_failed: 头衔名称过长，取消申请（$length$/18 bytes）
    apply_length_rejected: 头衔名称长度超出系统限定，请重新输入（$length$/18 bytes）
    apply_success: 申请头衔成功
    contents_prompt: 请输入头衔名称
    on_cooldown: 请在$TIME$后再申请或移除头衔
    on_err: 发送异常，申请头衔失败
    permission_denied: 你没有群管理员权限，@成员无效
    permission_rejected: 你没有群管理员权限，@成员无效，请重新输入
    remove_success: 移除头衔成功
bot:
  feedback:
    cancel: 已取消发送反馈
    failed: 反馈内容不可为空
    finish: 反馈信息已发送给 bot 管理员，感谢你的支持
    prompt: 请发送反馈信息
  reboot:
    cancel: 已取消重启
    failed: 未收到明确指示，已取消重启
    on_err: 发生异常，未能成功重启
    on_reboot: 正在执行重启
    prompt: 确认执行重启？
permission:
  owner:
    check_err: 检查 bot 信息失败
    check_false: 该 bot 未被设置为群主，无权执行该命令
